language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t thluiz10/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thluiz10/docker-react npm run test -- --coverage

#Pra usar quando tiver cartão pro aws
#Os carinhas em branco tem que completar com as infos depois
#deploy:
# provider: elasticbeanstalk
# region:
# app: docker-react
# env: Docker-env
# bucket_name:
# bucket_path:
# on:
#   branch: master
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key:
#   secure: $AWS_SECRET_KEY